### ISSUE TITLE
Could you give more detail about the install?

### ISSUE THREAD

**Issue by zwzhangdlut** [mathvansoest/CoastSnapPy#4]
Thanks for your works!
Since the software depends on many different library files, could you give the detailed versions of the libraries needed.

**Comment by mathvansoest** [comment]
Hi! The different libraries can be installed using the environment.yml file. More detailed explanation can be found in the readme. Let me know if that works for you.

**Comment by zwzhangdlut** [comment]
> Hi! The different libraries can be installed using the environment.yml file. More detailed explanation can be found in the readme. Let me know if that works for you.

Thanks for your response!  I have been installed all the dependence libraries.  As a beginner, I'm still on the way to run the program.   If it works, I will tell you.
